### ISSUE TITLE
Github vulnerability reporting

### ISSUE THREAD

**Issue by theresa-m** [ossf/secure-sw-dev-fundamentals#111]
Hello, first off thanks for putting together this great course! While completing it I though it may be useful to mention GitHub's vulnerability reporting mechanism that was recently released [1] in the chapter "Publicly State How to Send Vulnerability Reports". If you think this sounds reasonable I'd be happy to open a PR around this change.

[1] https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability

**Comment by david-a-wheeler** [comment]
Yes, I'd definitely be interested!
