### ISSUE TITLE
Are there any plans to provide videos of the content?

### ISSUE THREAD

**Issue by MaineC** [ossf/secure-sw-dev-fundamentals#17]
Disclaimer: I have been following OpenSSF only from the sidelines, so maybe that was discussed elsewhere already - didn't see anything related to my question in the issue tracker of this repository though.

tl;dr: Do you have any plans for publishing a video taped version of the training?

Background: I know people who are better at learning new content when hearing instead of seeing/ reading it. In addition I know several people who are consuming content like what is offered here when going for a walk. 

Over at the InnerSource Commons we have been working with O'Reilly to get our Learning Path videos recorded. The resulting material was published under a creative commons license. Given the fact that a lot of people have video equipment at home these days due to conferences and work in remote-first settings I would guess though that creating such a recording should be easier now than it was back in 2019.

If there's anything that can be done to support with that - happy to help.

**Comment by david-a-wheeler** [comment]
We don't *currently* have plans to do the whole course with video.

The problem with video is that it's costly to make & costly to update. SAFEcode has some great video courses that have become obsolete because it's so expensive to update anything.

**Comment by david-a-wheeler** [comment]
I originally planned to make a bunch of videos, but our in-house Linux Foundation training organization recommended against it, for the reasons I listed above. They make many videos, but they've found that they're not as helpful for this kind of content. They're also harder to translate as well. And... I think they were right.

So thanks so much for the suggestion, but for now this is "considered but we decided against it". I'll close this.

More comments welcome as always!

**Comment by MaineC** [comment]
Thank you for this feedback - as unfortunate as that is for the people that learn more easily hearing stuff as opposed to reading it I fully understand your point. Thank you for sharing the reasons behind that decision here.

As you were mentioning translations: If at any point in time you need any help with making a translation into German happen, please let me know.
